### ISSUE TITLE
1.20.2 PaperMC server. Run with error:

### ISSUE THREAD

**Issue by YosephFr** [LunarEclipseStudios/From-The-Fog#40]
[18:25:00 INFO]: Loaded 7 recipes
[18:25:00 ERROR]: Failed to load function watching:check
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown or incomplete command, see below for error at position 0: <--[HERE]
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown or incomplete command, see below for error at position 0: <--[HERE]
        at net.minecraft.commands.CommandFunction.fromLines(CommandFunction.java:119) ~[?:?]
        at net.minecraft.server.ServerFunctionLibrary.lambda$reload$2(ServerFunctionLibrary.java:80) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
[18:25:00 INFO]: Starting minecraft server version 1.20.2
[18:25:00 INFO]: Loading properties
[18:25:00 INFO]: This server is running Paper version git-Paper-260 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 1865625)

**Comment by AgentLoneStar007** [comment]
Same issue here.

**Comment by jignac05** [comment]
Same for me

**Comment by Bret06** [comment]
This is not a bug. Simply a check used to determine whether or not the datapack is working. It's good that you're seeing this, as it means it's installed correctly!
